# - Server -
server:
  port: 8080
  tomcat:
    accesslog:
      enabled: false
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false

# - Spring -
spring:
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/urban_trees
    username: ${db.user}
    password: ${db.password}
    platform: POSTGRESQL
    testWhileIdle: true
    validationQuery: select 1
    maxActive: 50
    maxAge: 60000
  jackson:
    date-format: "yyyy-MM-dd'T'HH-mm-ss"
    time-zone: UTC
    

# - MyBatis -
mybatis:
  mapperLocations: classpath*:**/mappers/*.xml
  typeAliasesPackage: at.sparklingscience.urbantrees.domain
  configuration:
    autoMappingBehavior: NONE

# - Logging -
logging:
  config: classpath:logback-spring.xml
  
# - Custom -
at:
  sparklingscience:
    urbantrees:
      dateFormatPattern: "yyyy-MM-dd'T'HH-mm-ss"
    