# - Server -
server:
  port: 8443
  tomcat:
    accesslog:
      enabled: false
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: ${keystore.password}
    key-alias: 1

# - Spring -
spring:
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/urban_trees
    username: ${db.user}
    password: ${db.password}
    platform: POSTGRESQL
    testWhileIdle: true
    validationQuery: select 1
    maxActive: 50
    maxAge: 60000
  jackson:
    date-format: "yyyy-MM-dd'T'HH-mm-ss"
    time-zone: UTC
  # File Upload
  servlet:
    http:
      multipart:
        max-file-size: 5MB
        max-request-size: 5MB
  security:
    require-ssl: false
    

# - MyBatis -
mybatis:
  mapperLocations: classpath*:**/mappers/*.xml
  typeAliasesPackage: at.sparklingscience.urbantrees.domain
  configuration:
    autoMappingBehavior: NONE

# - Logging -
logging:
  config: classpath:logback-spring.xml
  
# - Custom -
at:
  sparklingscience:
    urbantrees:
      dateFormatPattern: "yyyy-MM-dd'T'HH-mm-ss"
    