# - Server -
server:
  port: 8443
  tomcat:
    accesslog:
      enabled: false
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: ${keystore.password}
    key-alias: 1

# - Spring -
spring:
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/urban_trees
    username: ${db.user}
    password: ${db.password}
    platform: POSTGRESQL
    testWhileIdle: true
    validationQuery: select 1
    maxActive: 50
    maxAge: 60000
  # File Upload
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  #security:
  #  require-ssl: false
    

# - MyBatis -
mybatis:
  mapperLocations: classpath*:**/mappers/*.xml
  typeAliasesPackage: at.sparklingscience.urbantrees.domain
  configuration:
    autoMappingBehavior: NONE

# - Logging -
logging:
  config: classpath:logback-spring.xml
  
# - Custom -
at:
  sparklingscience:
    urbantrees:
      corsAllowedOriginPatterns: https://urban-tree-climate.sbg.ac.at:[80,443]
      dateFormatPattern: "yyyy-MM-dd'T'HH-mm-ss"
      otpIssuer: "urban-trees-climate.sbg.ac.at"
      loginQrUri: "https://urban-tree-climate.sbg.ac.at/login/{token}?pin=true"
      userContent:
        maxSavesPerUserPerDay: 100
    