# - Server -
server:
  port: 8080
  tomcat:
    accesslog:
      enabled: false
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false

# - Spring -
spring:
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/urban_trees
    username: ${db.user}
    password: ${db.password}
    platform: POSTGRESQL
    testWhileIdle: true
    validationQuery: select 1
    maxActive: 50
    maxAge: 60000
  # File Upload
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  #security:
  #  require-ssl: false
    

# - MyBatis -
mybatis:
  mapperLocations: classpath*:at/sparklingscience/urbantrees/mappers/*.xml
  typeAliasesPackage: at.sparklingscience.urbantrees.domain
  configuration:
    autoMappingBehavior: NONE

# - Logging -
logging:
  config: classpath:logback-spring.xml
  
# - Custom -
at:
  sparklingscience:
    urbantrees:
      corsAllowedOriginPatterns: https://cobs.laurenz.dev
      dateFormatPattern: "yyyy-MM-dd'T'HH-mm-ss"
      otpIssuer: "cobs.laurenz.dev"
      loginQrUri: "https://cobs.laurenz.dev/login/{token}?pin=true"
      userContent:
        maxSavesPerUserPerDay: 100
    