
#
# Version and API info
#

swagger: "2.0"
info:
  description: ""
  version: "0.0.2"
  title: "Urban Trees API"
  termsOfService: ""
  contact:
    email: "laurenz.fiala@outlook.at"
  license:
    name: ""
    url: "test://test"
host: "test.test"
basePath: "/test"
tags:
- name: "tree"
  description: "Retrieve and store tree information"
- name: "beacon"
  description: "Data corresponding to beacons and their data collection"
- name: "observation"
  description: "New observation data"
schemes:
- "https"

#
# Paths
#

paths:
  /tree/{treeId}:
    get:
      tags:
      - "tree"
      summary: "Return information about a single tree"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "treeId"
        in: "path"
        description: "ID of a tree"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/Tree"
        400:
          description: "Invalid tree id"
      security:
      - api_key: []

  /tree/{treeId}/physiognomy/:
    get:
      tags:
      - "tree"
      summary: "Return one or more physiognomy datasets, sorted by descending observation date (optionally in a given timespan)"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "treeId"
        in: "path"
        description: "ID of associated tree"
        required: true
        type: "integer"
        format: "int32"
      - name: "timespanMin"
        in: query
        description: "Oldest date"
        type: "integer"
        format: "int64"
      - name: "timespanMax"
        in: query
        description: "Newest date"
        type: "integer"
        format: "int64"
      responses:
          200:
            description: "Successful"
            schema:
              type: array
              items:
                $ref: "#/definitions/PhysiognomyDataset"
          400:
            description: "Invalid tree id"
      security:
      - api_key: []
    post:
      tags:
      - "tree"
      - "observation"
      summary: "Store a single physiognomy dataset"
      description: ""
      consumes:
      - "application/json"
      parameters:
      - name: "treeId"
        in: "path"
        description: "ID of associated tree"
        required: true
        type: "integer"
        format: "int32"
      - in: body
        name: body
        description: "Dataset to store"
        required: true
        schema:
          $ref: "#/definitions/PhysiognomyDataset"
      responses:
          201:
            description: "Successfully stored"
          400:
            description: "Invalid data"
            schema:
              $ref: "#/definitions/PostError"
      security:
      - api_key: []
      
  /tree/{treeId}/phenology/:
    get:
      tags:
      - "tree"
      summary: "Return one or more phenology datasets, sorted by descending observation date (optionally in a given timespan)"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "treeId"
        in: "path"
        description: "ID of associated tree"
        required: true
        type: "integer"
        format: "int32"
      - name: "timespanMin"
        in: query
        description: "Oldest date"
        type: "integer"
        format: "int64"
      - name: "timespanMax"
        in: query
        description: "Newest date"
        type: "integer"
        format: "int64"
      responses:
          200:
            description: "Successful"
            schema:
              type: array
              items:
                $ref: "#/definitions/PhenologyDataset"
          400:
            description: "Invalid tree id"
      security:
      - api_key: []
    post:
      tags:
      - "tree"
      - "observation"
      summary: "Store a single phenology dataset"
      description: ""
      consumes:
      - "application/json"
      parameters:
      - name: "treeId"
        in: "path"
        description: "ID of associated tree"
        required: true
        type: "integer"
        format: "int32"
      - in: body
        name: body
        description: "Dataset to store"
        required: true
        schema:
          $ref: "#/definitions/PhenologyDataset"
      responses:
          201:
            description: "Successfully stored"
          400:
            description: "Invalid data"
            schema:
              $ref: "#/definitions/PostError"
      security:
      - api_key: []

  /beacon/{beaconId}:
    get:
      tags:
      - "beacon"
      summary: "Return information about a single beacon"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "beaconId"
        in: "path"
        description: "Beacon identifier"
        required: true
        pattern: "\\d+"
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/Beacon"
        400:
          description: "Invalid beacon id"
      security:
      - api_key: []
      
  /beacon/{address}:
    get:
      tags:
      - "beacon"
      summary: "Return information about a single beacon"
      description: "Used for discovery of BLE beacons in the vicinity of the user"
      produces:
      - "application/json"
      parameters:
      - name: "address"
        in: "path"
        description: "Bluetooth address of a beacon"
        required: true
        pattern: "(?:[\\d\\w]{2}\\-){5}(?:[\\d\\w]{2})}"
        type: "string"
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/Beacon"
        400:
          description: "Invalid beacon address"
      security:
      - api_key: []

  /beacon/{beaconId}/data/:
    get:
      tags:
      - "beacon"
      summary: "Return one or more beacon datasets, sorted by descending observation date (optionally in a given timespan)"
      description: "Returns all stored datasets. If timespanMax is given, only returns up to that point. Same is valid for timespanMin."
      produces:
      - "application/json"
      parameters:
      - name: "beaconId"
        in: "path"
        description: "ID of corresponding beacon"
        required: true
        type: "integer"
        format: "int32"
      - name: "timespanMin"
        in: query
        description: "Oldest date"
        type: "integer"
        format: "int64"
      - name: "timespanMax"
        in: query
        description: "Newest date"
        type: "integer"
        format: "int64"
      responses:
          200:
            description: "Successful"
            schema:
              type: array
              items:
                $ref: "#/definitions/BeaconDataset"
          400:
            description: "Invalid beacon id"
          404:
            description: "No data found in given timespan"
      security:
      - api_key: []
    post:
      tags:
      - "beacon"
      summary: "Store one or more beacon datasets"
      description: ""
      consumes:
      - "application/json"
      parameters:
      - name: "beaconId"
        in: "path"
        description: "ID of corresponding beacon"
        required: true
        type: "integer"
        format: "int32"
      - in: body
        name: body
        description: "Datasets to store"
        required: true
        schema:
          type: array
          items:
            $ref: "#/definitions/BeaconDataset"
      responses:
        201:
          description: "Successfully stored"
        400:
          description: "Invalid data"
          schema:
            $ref: "#/definitions/PostError"
      security:
      - api_key: []

#
# Security
#

securityDefinitions:
  api_key:
    type: apiKey
    name: x-api-key
    in: header

#
# Definitions
#

definitions:
  
  # Entities
  Tree:
    type: "object"
    required:
      - "id"
      - "location"
      - "species"
      - "genus"
    properties:
      id:
        type: "integer"
        format: "int32"
      location:
        $ref: "#/definitions/TreeLocation"
      species:
        type: "string"
      genus:
        type: "string"
      plantationYear:
        description: "Latest observed plantation year"
        type: "integer"
        format: "int32"
      isPlantationYearEstimate:
        description: "Whether lastest observed plantationYear is an estimate or not"
        type: "boolean"
  
  PhysiognomyDataset:
    type: "object"
    required:
      - "treeId"
    properties:
      treeId:
        type: "integer"
        format: "int32"
      treeHeight:
        type: "integer"
        format: "int32"
      trunkCircumference:
        type: "integer"
        format: "int32"
      crownBase:
        type: "integer"
        format: "int32"
      crownWidth:
        type: "integer"
        format: "int32"
      observationDate:
        description: "UTC date and time string"
        type: "string"
  
  PhenologyDataset:
    type: "object"
    required:
      - "treeId"
    properties:
      treeId:
        type: "integer"
        format: "int32"
      observers:
        type: "string"
      observations:
        type: array
        items:
          $ref: "#/definitions/PhenologyObservation"
      observationDate:
        description: "UTC date and time string"
        type: "string"
        
  PhenologyObservation:
    type: "object"
    required:
      - "typeId"
      - "type"
      - "objectId"
      - "object"
      - "resultId"
      - "result"
    properties:
      typeId:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      objectId:
        type: "integer"
        format: "int32"
      object:
        type: "string"
      resultId:
        type: "integer"
        format: "int32"
      result:
        type: "string"
  
  Beacon:
    type: "object"
    required:
      - "id"
      - "treeId"
      - "bluetoothAddress"
    properties:
      id:
        type: "integer"
        format: "int32"
      treeId:
        type: "integer"
        format: "int32"
      bluetoothAddress:
        type: "string"
        
  BeaconDataset:
    type: "object"
    required:
      - "beaconId"
    properties:
      id:
        type: "integer"
        format: "int32"
      beaconId:
        type: "integer"
        format: "int32"
      humidity:
        type: "number"
        format: "float"
      temperature:
        type: "number"
        format: "float"
      observationDate:
        description: "UTC date and time string"
        type: "string"
      
  TreeLocation:
    type: "object"
    required:
      - "id"
    properties:
      id:
        type: "integer"
        format: "int32"
      coordinates:
        $ref: "#/definitions/Coordinates"
      street:
        type: "string"
      city:
        type: "string"
        
  Coordinates:
    type: "object"
    required:
      - "x"
      - "y"
    properties:
      x:
        type: "number"
        format: "float"
      y:
        type: "number"
        format: "float"
        
  # Error Responses
  PostError:
    type: "object"
    required:
      - "name"
      - "description"
      - "code"
    properties:
      name:
        description: "General error name"
        type: "string"
      description:
        description: "Specific error description"
        type: "string"
      code:
        description: "Application error code"
        type: "integer"
        format: "int32"
    